spring.application.name=med-easy

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/med-easy}

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO

security.jwt.secret=${JWT_SECRET:9f8c2a7e6b4d1c3a8e5f0d9b7a6c2e1f4a8b9c7d6e5f1a2b3c4d5e6f7a8b9c0d}
security.jwt.expiration-seconds=3600
