spring.application.name=med-easy

spring.mongodb.uri=${MONGODB_URI}

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-seconds=3600
